notifications:
  email: false

sudo: required
dist: trusty

before_install:
  - curl 'https://github.com/miloyip/rapidjson/archive/v1.1.0.tar.gz' | tar -x
  - sudo apt-get update -qq
  - sudo apt-get install -qq qtbase5-dev

compiler:
  - gcc
  - clang

script:
  - mkdir build
  - cd build
  - cmake -DRapidJSON_ROOT=rapidjson-1.1.0 ..
  - make -j
