platform: x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive

environment:
  QTDIR: C:\Qt\5.7\msvc2015_64

before_build:
  - set PATH=%PATH%;%QTDIR%\bin
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" ..

build:
  parallel: true
  project: build\qconread2.sln

artifacts:
  - path: build\$(configuration)\*
