platform: x64

configuration:
  - Debug
  - Release

install:
  - git submodule update --init --recursive
  - curl -O -L 'https://github.com/miloyip/rapidjson/archive/v1.0.2.zip'
  - 7z x v1.0.2.zip

environment:
  QTDIR: C:\Qt\5.7\msvc2015_64
  PATH: %PATH%;%QTDIR%\bin

before_build:
  - mkdir build
  - cd build
  - cmake -G "Visual Studio 14 2015 Win64" -DRapidJSON_ROOT=..\rapidjson-1.0.2 ..

build:
  parallel: true
  project: build\qconread2.sln

artefacts:
  - path: build\$(configuration)\*
